/**
 * @license Copyright (c) 2003-2005, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or http://ckeditor.com/license
 */

/**
 * This file was added automatically by CKEditor builder.
 * You may re-use it at any time to build CKEditor again.
 *
 * If you would like to build CKEditor online again
 * (for example to upgrade), visit one the following links:
 *
 * (0) http://ckeditor.com/builder
 *     Visit online builder to build CKEditor from scratch.
 *
 * (2) http://ckeditor.com/builder/e6b8a045f8f984a69463975ca3e6524a
 *     Visit online builder to build CKEditor, starting with the same setup as before.
 *
 * (3) http://ckeditor.com/builder/download/e6b8a045f8f984a69463975ca3e6524a
 *     Straight download link to the latest version of CKEditor (Optimized) with the same setup as before.
 *
 * NOTE:
 *    This file is not used by CKEditor, you may remove it.
 *    Changing this file will not change your CKEditor configuration.
 */

var CKBUILDER_CONFIG = {
	skin: 'moono',
	preset: 'full',
	ignore: [
		'.bender',
		'bender.js',
		'bender-err.log',
		'bender-out.log',
		'dev',
		'.DS_Store',
		'.editorconfig',
		'.gitattributes',
		'.gitignore',
		'gruntfile.js',
		'.idea',
		'.jscsrc',
		'.jshintignore',
		'.jshintrc',
		'less',
		'.mailmap',
		'node_modules',
		'package.json',
		'README.md',
		'tests'
	],
	plugins : {
		'a00yhelp' : 0,
		'about' : 0,
		'basicstyles' : 0,
		'bidi' : 0,
		'blockquote' : 0,
		'clipboard' : 0,
		'colorbutton' : 0,
		'colordialog' : 0,
		'contextmenu' : 0,
		'dialogadvtab' : 0,
		'div' : 0,
		'elementspath' : 0,
		'enterkey' : 0,
		'entities' : 0,
		'filebrowser' : 0,
		'find' : 0,
		'flash' : 0,
		'floatingspace' : 0,
		'font' : 0,
		'format' : 0,
		'forms' : 0,
		'horizontalrule' : 0,
		'htmlwriter' : 0,
		'iframe' : 0,
		'image' : 0,
		'indentblock' : 0,
		'indentlist' : 0,
		'justify' : 0,
		'language' : 0,
		'link' : 0,
		'list' : 0,
		'liststyle' : 0,
		'magicline' : 0,
		'maximize' : 0,
		'newpage' : 0,
		'pagebreak' : 0,
		'pastefromword' : 0,
		'pastetext' : 0,
		'preview' : 0,
		'print' : 0,
		'removeformat' : 0,
		'resize' : 0,
		'save' : 0,
		'scayt' : 0,
		'selectall' : 0,
		'showblocks' : 0,
		'showborders' : 0,
		'smiley' : 0,
		'sourcearea' : 0,
		'specialchar' : 0,
		'stylescombo' : 0,
		'tab' : 0,
		'table' : 0,
		'tabletools' : 0,
		'templates' : 0,
		'toolbar' : 0,
		'undo' : 0,
		'wsc' : 0,
		'wysiwygarea' : 0
	},
	languages : {
		'af' : 0,
		'ar' : 0,
		'bg' : 0,
		'bn' : 0,
		'bs' : 0,
		'ca' : 0,
		'cs' : 0,
		'cy' : 0,
		'da' : 0,
		'de' : 0,
		'el' : 0,
		'en' : 0,
		'en-au' : 0,
		'en-ca' : 0,
		'en-gb' : 0,
		'eo' : 0,
		'es' : 0,
		'et' : 0,
		'eu' : 0,
		'fa' : 0,
		'fi' : 0,
		'fo' : 0,
		'fr' : 0,
		'fr-ca' : 0,
		'gl' : 0,
		'gu' : 0,
		'he' : 0,
		'hi' : 0,
		'hr' : 0,
		'hu' : 0,
		'id' : 0,
		'is' : 0,
		'it' : 0,
		'ja' : 0,
		'ka' : 0,
		'km' : 0,
		'ko' : 0,
		'ku' : 0,
		'lt' : 0,
		'lv' : 0,
		'mk' : 0,
		'mn' : 0,
		'ms' : 0,
		'nb' : 0,
		'nl' : 0,
		'no' : 0,
		'pl' : 1,
		'pt' : 0,
		'pt-br' : 0,
		'ro' : 0,
		'ru' : 0,
		'si' : 0,
		'sk' : 0,
		'sl' : 0,
		'sq' : 0,
		'sr' : 0,
		'sr-latn' : 0,
		'sv' : 0,
		'th' : 0,
		'tr' : 0,
		'tt' : 0,
		'ug' : 0,
		'uk' : 0,
		'vi' : 0,
		'zh' : 0,
		'zh-cn' : 0
	}
};